import dongXu from './menuImage/dongXu.jpg'
const list = [
    {
      id: 1,
      title: "BÁNH BAO",
      author: "NHÂN PHÔ MAI: 1 cái",
      price: 25000,
      img: "https://thumbs.vikingscyber.com/288x288/vk-assets/media/438/highlight/MAEr7uJ3vUafz2OnzGfFIw.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "SANDWICH",
      author: ":2 cái",
      price: 40000,
      img: "https://m.media-amazon.com/images/I/71rmxx8P2qL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "BÚN THÁI",
      author: "CAY,KÈM RAU: 1 bát",
      price: 45000,
      img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "BÚN BÒ HUẾ",
      author: "1 bát",
      price: 40000,
      img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "BÁNH ĐỒNG XU",
      author: "1 cái",
      price: 30000,
      img: "https://m.media-amazon.com/images/I/71O-FI7QApL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "CƠM CHIÊN ĐÙI GÀ",
      author: "1 đĩa",
      price: 40000,
      img: "https://m.media-amazon.com/images/I/9173YBkMIsL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Ô LONG ĐÀO",
      author: "1 cốc",
      price: 30000,
      img: "https://m.media-amazon.com/images/I/913sv4sex3L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "SỮA KHOAI",
      author: "1 cốc",
      price: 30000,
      img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "PEPSI",
      author: "1 chai",
      price: 15000,
      img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "MATCHA",
      author: "1 cốc",
      price: 30000,
      img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "HỒNG TRÀ",
      author: "1 cốc",
      price: 30000,
      img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "COCA",
      author: "1 chai",
      price: 15000,
      img: '../menuImage/dongXu.jpg',
      amount: 1,
    },
];

export default list;